---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: wordpresses.wordpress.presslabs.org
spec:
  group: wordpress.presslabs.org
  names:
    kind: Wordpress
    plural: wordpresses
    shortNames:
    - wp
    singular: wordpress
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cliPodTemplate: {}
            contentVolumeSpec:
              properties:
                emptyDir: {}
                hostPath: {}
                persistentVolumeClaim: {}
            domains:
              description: Domains for this this site answers. The first item is set
                as the "main domain" (WP_HOME and WP_SITEURL constants).
              items:
                type: string
              type: array
            env:
              description: Env that gets injected into every container of WebPodTemplate
                and CLIPodTemplate
              items: {}
              type: array
            envFrom:
              description: EnvFrom gets injected into every container of WebPodTemplate
                and CLIPodTemplate
              items: {}
              type: array
            ingressAnnotations:
              description: If specified apply these annotations to the Ingress resource
                created for this Wordpress Site.
              type: object
            mediaVolumeSpec:
              properties:
                emptyDir: {}
                hostPath: {}
                persistentVolumeClaim: {}
            replicas:
              description: Number of desired web pods. This is a pointer to distinguish
                between explicit zero and not specified. Defaults to 1.
              format: int32
              type: integer
            serviceSpec: {}
            tlsSecretRef:
              description: TLSSecretRef a secret containing the TLS certificates for
                this site.
              type: string
            volumeMountsSpec:
              description: VolumeMountsSpec defines the mount structure for mounting
                volumes into pods. Each container in WebPodTemplate and CLIPodTemplate
                will get this structure mounted. If undefined, the /wp-content folder
                from ContentVolume gets mounted into /var/www/wp-content/ and if defined,
                the MediaVolume gets mounted into /var/www/wp-content/uploads
              items: {}
              type: array
            webPodTemplate: {}
          required:
          - domains
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
