---
apiVersion: v1
kind: Secret
metadata:
  name: mysite-db
type: Opaque
data:
  ROOT_PASSWORD: bm90LXNvLXNlY3VyZQ==
  USER: d29yZHByZXNz
  PASSWORD: d3AtaW5zZWN1cmU=
  DATABASE: d29yZHByZXNz
---
apiVersion: v1
kind: Secret
metadata:
  name: mysite-salt
type: Opaque
data:
  AUTH_KEY: RU5UOEBLUENENlNKJzkpaE1TKSx4V0tQSShvYENDbW5ZVkZoQEt9TE5TLzIwOjhPZGY5JSc2YTReY3p4a1g0LQ==
  SECURE_AUTH_KEY: MXJRLlZZQUtdcyk7KX5bKnskeixBe20uN3ZeXzFCby5TbU1Jdkh1VSFGSn10bjNwUWYmUmBdcylbMk9Tajp2LQ==
  LOGGED_IN_KEY: Sm4xdmVGSV0zP0pmPVUsN3llX1lacChvP2M3YWtlYiVEX3JZbk4jKEo+QGVAL1ZUdHd5aVlKbEBWaT1zcj11PQ==
  NONCE_KEY: Jm9eTn1oNTRKLn5pOTlbWHpqQ3tNJG53YVgneEFGPW1PPiYwdSRDVTFPLlB1RVc1NVZtcmRPfWMoYG43QmNNdg==
  AUTH_SALT: RnorP35BZFB3d3IwfVNsWnYsL0szZiE3Xj0tV2NQY20wc1IxZFpob2dfNnFqXn1tLjpDUmQzXV5XZCh3W1ApPw==
  SECURE_AUTH_SALT: QllpZVlrfkExRzFnWlpMUDI/aXJieyVifW0yP2BUP3Z0ZHwwJCFNS0klbEUsNGBUbWhjeE4sNVNge2Mzbzt5IQ==
  LOGGED_IN_SALT: QHNeZSJaSTU0PnNWKS9QOjxmWConIVRhMmwuWFpHO2QxV0xxQzBdY0NeTjFpNiU+PCEnYEA1ZT5KSy5oanl4Ug==
  NONCE_SALT: OCclcHg7UTIzZXdkVi9PJCsoVWZTWkUuTUwnZ2N3IzFPfGpZRWBAaD5VMTtbdnIzWHtSdnt4ZUVWcGtETnhzUQ==
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysite
spec:
  replicas: 1
  secretName: mysite-db
---
apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: mysite
spec:
  replicas: 1
  image: quay.io/presslabs/wordpress-runtime:4.9.8-php71
  secretRef: mysite
  tlsSecretRef: mysite-tls
  envFrom:
    - prefix: "WORDPRESS_"
      secretRef:
        name: mysite-salt
  env:
    - name: WORDPRESS_DB_HOST
      value: mysite-mysql-master
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          name: mysite-db
          key: USER
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysite-db
          key: PASSWORD
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          name: mysite-db
          key: DATABASE
  domains:
    - calin.localtest.me
