resources:
  - crds/wordpress.presslabs.org_wordpresses.yaml


patchesJson6902:
# https://github.com/kubernetes/kubernetes/issues/84880
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: wordpresses.wordpress.presslabs.org
  path: patches/volume.yaml

# https://github.com/kubernetes-sigs/controller-tools/issues/444
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: wordpresses.wordpress.presslabs.org
  path: patches/x-kubernetes-list-map-keys.yaml
