{{- if and .Values.crd.install (not (.Capabilities.APIVersions.Has "wordpress.presslabs.org/v1alpha1")) }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app: '{{ include "wordpress-operator.name" . }}'
    chart: '{{ include "wordpress-operator.chart" . }}'
    controller-tools.k8s.io: "1.0"
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: wordpresses.wordpress.presslabs.org
  annotations:
    helm.sh/hook: crd-install
spec:
  group: wordpress.presslabs.org
  names:
    kind: Wordpress
    plural: wordpresses
    shortNames:
    - wp
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            affinity:
              description: If specified, the pod's scheduling constraints
              type: object
            bootstrap:
              description: WordpressBootstrapSpec specifies credentials used to install
                wordpress, on the first run.
              properties:
                env:
                  description: Env defines environment variables for bootstrapping
                    WordPress +patchMergeKey=name +patchStrategy=merge
                  items:
                    type: object
                  type: array
                envFrom:
                  description: EnvFrom defines envFrom's which get passed into wordpress
                    bootstrapper
                  items:
                    type: object
                  type: array
              type: object
            code:
              description: CodeVolumeSpec specifies how the site's code gets mounted
                into the container. If not specified, a code volume won't get mounted
                at all.
              properties:
                contentSubPath:
                  description: ContentSubPath specifies where within the code volumes,
                    the wp-content folder resides.
                  type: string
                emptyDir:
                  description: EmptyDir to use if no HostPath is specified
                  type: object
                git:
                  description: GitDir specifies the git repo to use for code cloning.
                    It has the highest level of precedence over EmptyDir, HostPath
                    and PersistentVolumeClaim
                  properties:
                    emptyDir:
                      description: EmptyDir volume to use for git cloning.
                      type: object
                    env:
                      description: Env defines env variables  which get passed to
                        the git clone container +patchMergeKey=name +patchStrategy=merge
                      items:
                        type: object
                      type: array
                    envFrom:
                      description: EnvFrom defines envFrom which get passed to the
                        git clone container
                      items:
                        type: object
                      type: array
                    reference:
                      description: GitRef to clone (can be a branch name, but it should
                        point to a tag or a commit hash)
                      type: string
                    repository:
                      description: Repository is the git repository for the code
                      type: string
                  required:
                  - repository
                  type: object
                hostPath:
                  description: HostPath to use if no PersistentVolumeClaim is specified
                  type: object
                mountPath:
                  description: MountPath spechfies where should the code volume be
                    mounted. Defaults to /var/www/site/web/wp-content
                  type: string
                persistentVolumeClaim:
                  description: PersistentVolumeClaim to use if no GitDir is specified
                  type: object
                readOnly:
                  description: ReadOnly specifies if the volume should be mounted
                    read-only inside the wordpress runtime container
                  type: boolean
              type: object
            domains:
              description: Domains for which this this site answers. The first item
                is set as the "main domain" (eg. WP_HOME and WP_SITEURL constants).
              items:
                type: string
              minItems: 1
              type: array
            env:
              description: Env defines environment variables which get passed into
                web and cli pods +patchMergeKey=name +patchStrategy=merge
              items:
                type: object
              type: array
            envFrom:
              description: EnvFrom defines envFrom's which get passed into web and
                cli containers
              items:
                type: object
              type: array
            image:
              description: WordPress runtime image to use. Defaults to quay.io/presslabs/wordpress-runtime
              type: string
            imagePullPolicy:
              description: ImagePullPolicy overrides WordpressRuntime spec.imagePullPolicy
              enum:
              - Always
              - IfNotPresent
              - Never
              type: string
            imagePullSecrets:
              description: ImagePullSecrets defines additional secrets to use when
                pulling images
              items:
                type: object
              type: array
            ingressAnnotations:
              description: IngressAnnotations for this Wordpress site
              type: object
            media:
              description: MediaVolumeSpec specifies how media files get mounted into
                the runtime container. If not specified, a media volume won't be mounted
                at all.
              properties:
                emptyDir:
                  description: EmptyDir to use if no HostPath is specified
                  type: object
                gcs:
                  description: GCSVolumeSource specifies the google cloud storage
                    object storage configuration for media files. It has the highest
                    level of precedence over EmptyDir, HostPath and PersistentVolumeClaim
                  properties:
                    bucket:
                      description: Bucket for storing media files
                      minLength: 1
                      type: string
                    env:
                      description: 'Env variables for accessing gcs bucket. Taken
                        into account are: GOOGLE_APPLICATION_CREDENTIALS_JSON +patchMergeKey=name
                        +patchStrategy=merge'
                      items:
                        type: object
                      type: array
                    prefix:
                      description: PathPrefix is the prefix for media files in bucket
                      type: string
                  required:
                  - bucket
                  type: object
                hostPath:
                  description: HostPath to use if no PersistentVolumeClaim is specified
                  type: object
                persistentVolumeClaim:
                  description: PersistentVolumeClaim to use if no S3VolumeSource or
                    GCSVolumeSource are specified
                  type: object
              type: object
            nodeSelector:
              description: If specified, Pod node selector
              type: object
            priorityClassName:
              description: If specified, indicates the pod's priority class
              type: string
            replicas:
              description: Number of desired web pods. This is a pointer to distinguish
                between explicit zero and not specified. Defaults to 1.
              format: int32
              type: integer
            resources:
              description: 'If specified, the resources required by wordpress container.
                More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
              type: object
            serviceAccountName:
              description: 'ServiceAccountName is the name of the ServiceAccount to
                use to run this site''s pods More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/'
              type: string
            tag:
              description: Image tag to use. Defaults to latest
              type: string
            tlsSecretRef:
              description: TLSSecretRef a secret containing the TLS certificates for
                this site.
              type: string
            tolerations:
              description: If specified, the pod's tolerations.
              items:
                type: object
              type: array
            volumeMounts:
              description: VolumeMountsSpec defines additional mounts which get injected
                into web and cli pods.
              items:
                type: object
              type: array
            volumes:
              description: Volumes defines additional volumes to get injected into
                web and cli pods
              items:
                type: object
              type: array
          required:
          - domains
          type: object
        status:
          properties:
            conditions:
              description: Conditions represents the Wordpress resource conditions
                list.
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of Wordpress condition.
                    type: string
                required:
                - type
                - status
                - lastTransitionTime
                - reason
                - message
                type: object
              type: array
            replicas:
              description: Total number of non-terminated pods targeted by web deployment
                This is copied over from the deployment object
              format: int32
              type: integer
          type: object
  version: v1alpha1
{{- end }}
